# Welcome to Jekyll!
#
# This file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. 
# If you change this file, please restart the server process.

# Global Site settings, under site.<setting>
title:            "the polarysektion"
description:      "This is the beyond bleeding edge of the polarysektion, but somehow you found it!"
baseurl:          "" # the subpath of your site, e.g. /blog
url:              "" # the base hostname & protocol for your site, e.g. http://example.com

owner:
  email:           #
  github:          polarysekt
  stackexchange:   4801256
  youtube:         polarysekt
  soundcloud:      polarysekt

github_username:    polarysekt


timezone:           America/Chicago
future:             false  # publish future dated posts --  true, false (default) 
highlighter:        rouge
markdown:           kramdown

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jekyll-admin
sass:
  sass_dir: assets/css
  style: compressed

permalink: /blog/:title

collections:
  pinned:
    output: true
    permalink: /blog/:collection/:name

include: 
  - .htaccess
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - vendor
  - _site
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
